import os
import sqlite3
import snowflake.connector
import openai
from flask import Flask, request, jsonify
from datetime import datetime
from dotenv import load_dotenv
from contextlib import closing
from pandasai import SmartDataframe
import pandas as pd
import matplotlib.pyplot as plt
from langchain_community.chat_models import ChatOpenAI
import os
import base64
import io
import logging
import matplotlib
matplotlib.use('Agg')  # Prevents GUI errors

# Load environment variables
load_dotenv()

app = Flask(__name__)
openai.api_key = os.getenv("OPEN_API_KEY")
llm = ChatOpenAI(model_name="gpt-4", openai_api_key=os.getenv("OPEN_API_KEY"))
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")


SNOWFLAKE_CONFIG = {
    "user": 'sriks',
    "password": 'Srikanth05052005',
    "account": 'iognsgx-vq69326',
    "warehouse": 'COMPUTE_WH',
    "database": 'MEC',
    "schema":'SALES',
}

def init_db():
    with closing(sqlite3.connect("database.db")) as conn, closing(conn.cursor()) as cursor:
        cursor.executescript('''
            CREATE TABLE IF NOT EXISTS conversations (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                title TEXT,
                timestamp TEXT
            );
            CREATE TABLE IF NOT EXISTS messages (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                conversation_id INTEGER,
                role TEXT,
                content TEXT,
                timestamp TEXT,
                FOREIGN KEY(conversation_id) REFERENCES conversations(id) ON DELETE CASCADE
            );
        ''')
        conn.commit()

# Snowflake connection management
def get_snowflake_connection():
    try:
        return snowflake.connector.connect(**SNOWFLAKE_CONFIG)
    except snowflake.connector.errors.Error as e:
        logging.error(f"Snowflake connection error: {e}")
        return None
def execute_snowflake_query(query):
    conn = get_snowflake_connection()
    if not conn:
        return {"error": "Failed to connect to Snowflake."}, 500

    try:
        with conn.cursor() as cursor:
            cursor.execute(query)
            columns = [desc[0] for desc in cursor.description]  # Extract column names
            results = cursor.fetchall()
            
            # Convert results into list of dictionaries (column_name -> value)
            formatted_results = [dict(zip(columns, row)) for row in results]

            return {"results": formatted_results}
    except snowflake.connector.errors.ProgrammingError as e:
        logging.error(f"Snowflake query error: {e}")
        return {"error": "Invalid SQL query."}, 400
    except Exception as e:
        logging.error(f"Unexpected error: {e}")
        return {"error": "An unexpected error occurred."}, 500
    finally:
        conn.close()


def save_message(conversation_id, role, content):
    try:
        with closing(sqlite3.connect("database.db")) as conn, closing(conn.cursor()) as cursor:
            cursor.execute("""
                INSERT INTO messages (conversation_id, role, content, timestamp)
                VALUES (?, ?, ?, ?)
            """, (conversation_id, role, content, datetime.now().strftime("%Y-%m-%d %H:%M:%S")))
            conn.commit()
    except sqlite3.Error as e:
        print(f"Database error: {e}")


# Define the system message to guide the model
SYSTEM_MESSAGE = """
INSTRUCTIONS: Analyze the database schema and generate the SQL query accordingly. If asked any non-related question, do not generate an SQL query and respond accordingly.
- ONLY RETURN THE RAW SQL QUERY. DO NOT INCLUDE ANY EXPLANATIONS, MARKDOWN BACKTICKS, OR ADDITIONAL TEXT.
- Ensure the query ends with a semicolon (;).
- Optimize performance by minimizing unnecessary operations.
- Use IN, ON, BY operators as per applicable conditions and subqueries.
- If a query involves multiple steps or conditions, consider breaking it into subqueries or using CTEs.
- SCHEMA-RESTRICTED QUERIES: Only use tables and columns that exist in the schema.
- Return an error if a requested table or column is not found.
- MONTH HANDLING: Use numerical values for months instead of LIKE %pattern%.
- FOR STRING HANDLING: Convert strings to lowercase and use LIKE %pattern% for matching.
- JOIN REQUESTS: Interpret "along" as a request to join tables using valid schema relationships.
- VALIDATION: If a table or column does not exist, diagnose the error and then give me possible issue and return issue do not use the word "Error"
- USER QUERY CHECK:When the user asks a question, check if the question is related to the schema.
- SQL INJECTION: IF user for any sql injection queries return "Permission denied"
- QUERY VALIDATION: Validate the query to ensure it is syntactically correct.
- ABOUT DATABASE: This is a supermarket database where all tables are linked. If the user does not mention a table name in their query, intelligently determine the most relevant table(s) based on the context before generating the SQL query.

Database Schema:
Database name:SALES
ADVANCEBALANCE (ADVANCEBALANCEID NUMBER PRIMARY KEY,VOUCHERID NUMBER,BALANCE NUMBER,ISACTIVE BOOLEAN)
APILIST (APINAME TEXT PRIMARY KEY,SERVER TEXT,APIURL TEXT,ACCESSBY TEXT,CREDENTIAL TEXT)
AREA (AREAID NUMBER PRIMARY KEY,DESCRIPTIONS TEXT,ISACTIVE BOOLEAN)
AUTOMATETASK (AUTOMATELISTID NUMBER PRIMARY KEY,AUTOMATEDESCRIPTIONS TEXT,REQUIREDCOLUMNS TEXT,ISACTIVE BOOLEAN,ISTESTED BOOLEAN,ISOFFICEUSEONLY BOOLEAN)
BANK (BANKID NUMBER PRIMARY KEY,DESCRIPTIONS TEXT,ISACTIVE BOOLEAN)
BANKACCOUNT (BANKACCOUNTID NUMBER PRIMARY KEY,BANKNAME TEXT,STOREID NUMBER,ISACTIVE BOOLEAN,RTGSNEFTFORMAT TEXT,ISINCLUDEPAYEENAMEONNEFTCHQ BOOLEAN,FOREIGN KEY (STOREID) REFERENCES STORE(STOREID))
BANKBOOK (BANKBOOKID NUMBER PRIMARY KEY,DATE TIMESTAMP_NTZ,CREDIT NUMBER,DEBIT NUMBER,BALANCE NUMBER,USERID NUMBER,PARTICULARS TEXT,BANKACCOUNTID NUMBER,FOREIGN KEY (USERID) REFERENCES USER(USERID),FOREIGN KEY (BANKACCOUNTID) REFERENCES BANKACCOUNT(BANKACCOUNTID))
BARCODE (BARCODEID NUMBER PRIMARY KEY,PRODUCTCODE NUMBER,BARCODE TEXT,ISACTIVE BOOLEAN,FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE))
BARCODECONFLICT (CONFLICTID NUMBER PRIMARY KEY,BARCODE NUMBER,PRODUCTCODE1 NUMBER,PRODUCTCODE2 NUMBER,FOREIGN KEY (PRODUCTCODE1) REFERENCES PRODUCT(PRODUCTCODE),FOREIGN KEY (PRODUCTCODE2) REFERENCES PRODUCT(PRODUCTCODE))
BATCH (BATCHID NUMBER PRIMARY KEY,PRODUCTCODE NUMBER,FREEPRODUCTCODE NUMBER,EXPIRYDATE DATE,STOCKQTY NUMBER,FOCQTY NUMBER,RECEIVEDQTY NUMBER,BASECOST NUMBER,PURCHASEPRICEWITHTAX NUMBER,NETPURCHASEPRICE NUMBER,LIVEPRICE NUMBER,SALEPRICE NUMBER,WHOLESALEPRICE1 NUMBER,WHOLESALEPRICE2 NUMBER,WHOLESALEPRICE3 NUMBER,MRP NUMBER,TAXID NUMBER,STOREID NUMBER,SUPPLIERID NUMBER,MINQTY NUMBER,MAXQTY NUMBER,ORDERQTY NUMBER,GRNNUMBER TEXT,LASTBILLNO NUMBER,REGDISPERCENTAGE NUMBER,REGDISAMOUNT NUMBER,SPLDISPERCENTAGE NUMBER,SPLDISAMOUNT NUMBER,ISACTIVE BOOLEAN,ISSYNCED BOOLEAN,FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE),FOREIGN KEY (FREEPRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE),FOREIGN KEY (TAXID) REFERENCES TAX(TAXID),FOREIGN KEY (STOREID) REFERENCES STORE(STOREID),FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIER(SUPPLIERID))
BILLPAYMODE (PAYMODEID NUMBER PRIMARY KEY,DESCRIPTION TEXT,ISACTIVE BOOLEAN,ISONLINE BOOLEAN)
BILLRETURN (RETURNDATE TIMESTAMP_NTZ,BILLNO NUMBER,PRODUCTCODE NUMBER,QUANTITY NUMBER,MRP NUMBER,SELLINGPRICE NUMBER,RETURNUSERID NUMBER,ISACTIVE BOOLEAN,PRIMARY KEY (BILLNO, PRODUCTCODE),FOREIGN KEY (BILLNO) REFERENCES PRODUCTSALE(BILLNO),FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE),FOREIGN KEY (RETURNUSERID) REFERENCES USER(USERID))
BILLVALUEOFFER (BILLVALUEOFFERID NUMBER PRIMARY KEY,NAME TEXT,FROMDATE TIMESTAMP_NTZ,TODATE TIMESTAMP_NTZ,MINBILLVALUE NUMBER,ISACTIVE BOOLEAN,CREATEDUSERID NUMBER,MODIFIEDUSERID NUMBER,CREATEDDATE TIMESTAMP_NTZ,MODIFIEDDATE TIMESTAMP_NTZ,VALIDATETIME BOOLEAN,FOREIGN KEY (CREATEDUSERID) REFERENCES USER(USERID),FOREIGN KEY (MODIFIEDUSERID) REFERENCES USER(USERID))
BILLVALUEOFFERDETAIL (BILLVALUEOFFERDETAILID NUMBER PRIMARY KEY,BILLVALUEOFFERID NUMBER,PRODUCTCODE NUMBER,OFFERPRICE NUMBER,ISACTIVE BOOLEAN,OFFERQUANTITY NUMBER,FOREIGN KEY (BILLVALUEOFFERID) REFERENCES BILLVALUEOFFER(BILLVALUEOFFERID),FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE))
BRAND (BRANDID NUMBER PRIMARY KEY,DESCRIPTIONS TEXT,ISACTIVE BOOLEAN)
CANCELBILLLOG (LOGTIME TIMESTAMP_NTZ,TYPEOFCANCEL TEXT,BILLAMOUNT NUMBER,USERID NUMBER,FOREIGN KEY (USERID) REFERENCES USER(USERID))
CANCELVOUCHERPAYMENT (VOUCHERPAYMENTID NUMBER PRIMARY KEY,PAYMENTDATE DATE,PAYMODEID NUMBER,PAIDTO TEXT,CHEQUENO NUMBER,CHEQUEDATE DATE,BANKID TEXT,AREAID TEXT,PAIDAMOUNT NUMBER,ISCHEQUEPRINT BOOLEAN,BANKACCOUNTID NUMBER,ISCHEQUEISSUE BOOLEAN,ISCHEQUEPAID BOOLEAN,PRINTEDON TEXT,ISSUEDON TEXT,PAIDON TEXT,CANCELLEDON TIMESTAMP_NTZ,CANCELLEDBY TEXT,PRINTCOUNT NUMBER,FOREIGN KEY (PAYMODEID) REFERENCES PAYMODE(PAYMODEID),FOREIGN KEY (BANKACCOUNTID) REFERENCES BANKACCOUNT(BANKACCOUNTID))
CANCELVOUCHERPAYMENTDETAIL (VOUCHERPAYMENTDETAILID NUMBER PRIMARY KEY,VOUCHERPAYMENTID NUMBER,INVOICENO NUMBER,INVOICEDATE DATE,VOUCHERHEADID NUMBER,PARTICULARS TEXT,AMOUNT NUMBER,RECEIPTENTRYID NUMBER,PAYMENTTYPEID NUMBER,CASHWITHOUTTAX TEXT,TAXID TEXT,GSTNUMBER TEXT,TAXAMOUNT NUMBER,FOREIGN KEY (VOUCHERPAYMENTID) REFERENCES CANCELVOUCHERPAYMENT(VOUCHERPAYMENTID),FOREIGN KEY (PAYMENTTYPEID) REFERENCES PAYMENTTYPE(PAYMENTTYPEID),FOREIGN KEY (RECEIPTENTRYID) REFERENCES RECEIPTENTRY(RECEIPTENTRYID))
CASH (CASHID NUMBER PRIMARY KEY,CASHNAME NUMBER,ISACTIVE BOOLEAN)
CASHBOOK (CASHBOOKID NUMBER PRIMARY KEY,DATE TIMESTAMP_NTZ,CREDIT NUMBER,DEBIT NUMBER,BALANCE NUMBER,USERID NUMBER,PARTICULARS TEXT,FOREIGN KEY (USERID) REFERENCES USER(USERID))
CASHFLOWWAREHOUSE (ID NUMBER PRIMARY KEY,DATE TEXT,OPENINGBALANCE NUMBER,SALES NUMBER,SALESRETURN NUMBER,PAYMENT NUMBER,CONSIGNMENTPAYMENT NUMBER,CREDITBILLCREDIT NUMBER,CREDITBILLDEBIT NUMBER,CREDITBILLBALANCE NUMBER,VOUCHERPAYMENT NUMBER,SHELFRENT NUMBER,TOTALAMOUNTRECEIVED NUMBER,TOTALAMOUNTPAID NUMBER,TOTALAMOUNT NUMBER,CLOSINGBALANCE NUMBER,CASHCREDIT NUMBER,CASHDEBIT NUMBER,CASHBALANCE NUMBER,BANKCREDIT NUMBER,BANKDEBIT NUMBER,BANKBALANCE NUMBER)
CATEGORY (CATEGORYID NUMBER PRIMARY KEY, DEPARTMENTID NUMBER, DESCRIPTIONS TEXT, ISACTIVE BOOLEAN, FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENT(DEPARTMENTID));
CITY (CITYID NUMBER PRIMARY KEY, DESCRIPTIONS TEXT, ISACTIVE BOOLEAN);
COMBOOFFER (OFFERID NUMBER PRIMARY KEY, OFFERNAME TEXT, FROMDATE DATE, TODATE DATE, OFFERPRICE NUMBER, PRIORITY NUMBER, ISACTIVE BOOLEAN, ACTUALPRICE NUMBER);
COMBOOFFERDETAIL (OFFERDETAILID NUMBER PRIMARY KEY, OFFERID NUMBER, PRODUCTCODE NUMBER, QTY NUMBER, MRP NUMBER, SALEPRICE NUMBER, PURCHASEPRICE NUMBER, ISACTIVE BOOLEAN, FOREIGN KEY (OFFERID) REFERENCES COMBOOFFER(OFFERID), FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE));
COMBOOFFERSALEDETAIL (CREATEDDATE TIMESTAMP_NTZ, BILLNO NUMBER, OFFERID NUMBER, QUANTITY NUMBER, OFFERPRICE NUMBER, ACTUALPRICE NUMBER, ISACTIVE BOOLEAN, PRIMARY KEY (BILLNO, OFFERID), FOREIGN KEY (BILLNO) REFERENCES PRODUCTSALE(BILLNO), FOREIGN KEY (OFFERID) REFERENCES COMBOOFFER(OFFERID));
CORPORATECOUPON (CORPORATECOUPONID NUMBER PRIMARY KEY, DESCRIPTION TEXT, FROMDATE DATE, TODATE DATE, AMOUNT NUMBER, ISUSED BOOLEAN, ISACTIVE BOOLEAN);
COUPON (COUPONID NUMBER PRIMARY KEY, COUPONGROUP TEXT, DESCRIPTION TEXT, FROMDATE DATE, TODATE DATE, MINBILLAMT NUMBER, COUPONAMOUNT NUMBER, ONETIMEOFFER BOOLEAN, ISACTIVE BOOLEAN, ISUSED BOOLEAN, ISGROUPCOUPON BOOLEAN, ISONLINECOUPON BOOLEAN);
CUSTOMER (CUSTOMERCODE NUMBER PRIMARY KEY, CUSTOMERNAME TEXT, CUSTOMERTYPEID NUMBER, MOBILENO NUMBER, SEXID NUMBER, ADDRESS1 TEXT, ADDRESS2 NUMBER, AREAID NUMBER, CITYID NUMBER, STATEID NUMBER, PINCODE NUMBER, EMAILID TEXT, GSTNUMBER TEXT, PANNUMBER NUMBER, TOTALPOINT NUMBER, REDEEMEDPOINT NUMBER, BALANCEPOINT NUMBER, CREDITLIMIT TEXT, ISALLOWCREDIT BOOLEAN, ISALLOWDISCOUNT TEXT, CREATEDUSERID TEXT, CREATEDDATE TIMESTAMP_NTZ, MODIFIEDUSERID NUMBER, MODIFIEDDATE TEXT, ISACTIVE BOOLEAN, FOREIGN KEY (CUSTOMERTYPEID) REFERENCES CUSTOMERTYPE(CUSTOMERTYPEID),FOREIGN KEY (SEXID) REFERENCES SEX(SEXID),FOREIGN KEY (AREAID) REFERENCES AREA(AREAID),FOREIGN KEY (CITYID) REFERENCES CITY(CITYID),FOREIGN KEY (STATEID) REFERENCES STATE(STATEID),FOREIGN KEY (CREATEDUSERID) REFERENCES USER(USERID),FOREIGN KEY (MODIFIEDUSERID) REFERENCES USER(USERID))
CUSTOMERACCOUNT (CUSTOMERACCOUNTID NUMBER PRIMARY KEY, CUSTOMERCODE NUMBER, DATE TIMESTAMP_NTZ, BILLNO NUMBER, CREDIT NUMBER, DEBIT NUMBER, BALANCEAMOUNT NUMBER, RECENTLYDEBITAMOUNT NUMBER, DEBITEDUSERID TEXT, ISACTIVE BOOLEAN, FOREIGN KEY (CUSTOMERCODE) REFERENCES CUSTOMER(CUSTOMERCODE), FOREIGN KEY (BILLNO) REFERENCES PRODUCTSALE(BILLNO));
CUSTOMERPAYMENT (CUSTOMERPAYMENTNO NUMBER PRIMARY KEY, PAYMENTDATE TIMESTAMP_NTZ, CUSTOMERCODE NUMBER, PAYMODEID NUMBER, CHQDDNO TEXT, CHQDDDATE TEXT, BANKID TEXT, PLACEID TEXT, PAIDAMOUNT NUMBER, DISCOUNTAMOUNT NUMBER, RETURNNO TEXT, RETURNAMOUNT TEXT, USERID NUMBER, ISCHEQUEPRINT BOOLEAN, BANKACCOUNTID TEXT, FOREIGN KEY (CUSTOMERCODE) REFERENCES CUSTOMER(CUSTOMERCODE), FOREIGN KEY (PAYMODEID) REFERENCES PAYMODE(PAYMODEID), FOREIGN KEY (USERID) REFERENCES USER(USERID));
CUSTOMERPAYMENTDETAIL (CUSTOMERPAYMENTDETAILID NUMBER PRIMARY KEY, CUSTOMERPAYMENTNO NUMBER, BILLNO NUMBER, AMOUNT NUMBER, ISACTIVE BOOLEAN, FOREIGN KEY (CUSTOMERPAYMENTNO) REFERENCES CUSTOMERPAYMENT(CUSTOMERPAYMENTNO), FOREIGN KEY (BILLNO) REFERENCES PRODUCTSALE(BILLNO));
CUSTOMERTYPE (CUSTOMERTYPEID NUMBER PRIMARY KEY, DESCRIPTIONS TEXT, ISACTIVE BOOLEAN);
DELETEDPRODUCT (PRODUCTCODE NUMBER PRIMARY KEY, PRODUCTNAME TEXT, PRODUCTSHORTNAME TEXT, SUPPLIERID NUMBER, SUBCATEGORYID NUMBER, BRANDID NUMBER, MANUFACTURERID NUMBER, UOMID NUMBER, CASEQTY NUMBER, BAYID NUMBER, SHELFID NUMBER, HSNCODE NUMBER, TAXID NUMBER, MINQTY NUMBER, MAXQTY NUMBER, ORDERQTY NUMBER, PRODUCTIONCOST NUMBER, MRP NUMBER, PURCHASEPRICE NUMBER, PURCHASEPRICEWITHTAX NUMBER, DISCOUNTPERCENTAGE NUMBER, DISCOUNTAMOUNT NUMBER, SPLDISPERCENTAGE NUMBER, SPLDISAMOUNT NUMBER, MARGINTYPE TEXT, SALEPRICE NUMBER, WHOLESALEPRICE1 NUMBER, WHOLESALEPRICE2 NUMBER, WHOLESALEPRICE3 NUMBER, SALEPRICEPERCENTAGE NUMBER, WHOLESALEPRICE1PERCENTAGE NUMBER, WHOLESALEPRICE2PERCENTAGE NUMBER, WHOLESALEPRICE3PERCENTAGE NUMBER, SALEPRICEPERAMOUNT NUMBER, WSPRICE1PERAMOUNT NUMBER, WSPRICE2PERAMOUNT NUMBER, WSPRICE3PERAMOUNT NUMBER, ISPARENT BOOLEAN, WEIGHT NUMBER, PARENTPRODUCTCODE NUMBER, ISEXPIRE BOOLEAN, EXPIRYDAYS NUMBER, ISALLOWFRACTION BOOLEAN, ISFREE BOOLEAN, ISLOYALTY BOOLEAN, ISBATCH BOOLEAN, ISMEMBERDISCOUNT BOOLEAN, ISCHECKSTOCK BOOLEAN, ISAUTOPOALLOWED BOOLEAN, ISSHOWPURCHASERETURN BOOLEAN, ISSHOWSALESRETURN BOOLEAN, ISSHOWBILLING BOOLEAN, ISSHOWGRN BOOLEAN, ISSHOWPO BOOLEAN, ISACTIVE BOOLEAN, ISTHIRDPARTYPRODUCT BOOLEAN, ISCOMBO BOOLEAN, ISHIDEONLINE BOOLEAN, CREATEDUSERID NUMBER, CREATEDDATE TIMESTAMP_NTZ, MODIFIEDUSERID NUMBER, MODIFIEDDATE TIMESTAMP_NTZ, STOCKDAYS NUMBER, FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIER(SUPPLIERID),FOREIGN KEY (SUBCATEGORYID) REFERENCES SUBCATEGORY(SUBCATEGORYID),FOREIGN KEY (BRANDID) REFERENCES BRAND(BRANDID),FOREIGN KEY (MANUFACTURERID) REFERENCES MANUFACTURER(MANUFACTURERID),FOREIGN KEY (UOMID) REFERENCES UOM(UOMID),FOREIGN KEY (SHELFID) REFERENCES SHELF(SHELFID),FOREIGN KEY (TAXID) REFERENCES TAX(TAXID),FOREIGN KEY (CREATEDUSERID) REFERENCES USER(USERID),FOREIGN KEY (MODIFIEDUSERID) REFERENCES USER(USERID))
DELIVERYSCHEDULE (DELIVERYSCHEDULEID NUMBER PRIMARY KEY, DESCRIPTIONS TEXT, STOCKDAYS NUMBER, ISACTIVE BOOLEAN)
DEPARTMENT (DEPARTMENTID NUMBER PRIMARY KEY, DESCRIPTIONS TEXT, ISACTIVE BOOLEAN);
DISCOUNTELIGIBLE (PRODUCTCODE NUMBER PRIMARY KEY, ISDISCOUNT BOOLEAN, FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE));
DISCOUNTTYPE (DISCOUNTTYPEID NUMBER PRIMARY KEY, DESCRIPTIONS TEXT, DISCOUNTPERCENT NUMBER, ISACTIVE BOOLEAN);
DUPLICATEPRODUCT (DPID NUMBER PRIMARY KEY, OLDPRODUCTCODE NUMBER, NEWPRODUCTCODE NUMBER, UPDATEDATE TIMESTAMP_NTZ, ISVERIFIED BOOLEAN, ISUPDATED BOOLEAN, FOREIGN KEY (OLDPRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE), FOREIGN KEY (NEWPRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE));
EMPLOYEE (EMPLOYEECODE NUMBER PRIMARY KEY, EMPLOYEENAME TEXT, DESIGNATION TEXT, DEPARTMENT TEXT, DOJ DATE, DOR DATE, ISACTIVE BOOLEAN);
EXPENSE (EXPENSEID NUMBER PRIMARY KEY, DESCRIPTIONS TEXT, ISACTIVE BOOLEAN)
FORMS (FORMID NUMBER PRIMARY KEY, FORMNAME TEXT, MODULEID NUMBER, ISACTIVE BOOLEAN, FOREIGN KEY (MODULEID) REFERENCES MODULE(MODULEID));
GROCERYPRICECHANGE (PRICECHANGENO NUMBER PRIMARY KEY, CREATEDDATE TIMESTAMP_NTZ, USERID NUMBER, ISACTIVE BOOLEAN, ISSYNC BOOLEAN, FOREIGN KEY (USERID) REFERENCES USER(USERID));
GROCERYPRICECHANGEDETAIL (GROCERYPRICECHANGEID NUMBER PRIMARY KEY, PRICECHANGENO NUMBER, PRODUCTCODE NUMBER, LIVEPRICE FLOAT, SALEPRICE FLOAT, WSPRICE1 FLOAT, WSPRICE2 FLOAT, WSPRICE3 FLOAT, MRP NUMBER, ISACTIVE BOOLEAN, ISSYNC BOOLEAN, FOREIGN KEY (PRICECHANGENO) REFERENCES GROCERYPRICECHANGE(PRICECHANGENO), FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE));
HOLDBILL (HOLDBILLNO NUMBER PRIMARY KEY, HOLDBILLDATE TIMESTAMP_NTZ, BILLAMOUNT FLOAT, CUSTOMERCODE NUMBER, MOBLILENO NUMBER, DISCOUNTPERCENTAGE FLOAT, REDEEMPOINTS TEXT, COUPON NUMBER, OTHERAMOUNT NUMBER, STOREID NUMBER, ISBILL BOOLEAN, CREATEDUSERID NUMBER, TOTALBILLTIMESEC NUMBER, ISACTIVE BOOLEAN, FOREIGN KEY (CUSTOMERCODE) REFERENCES CUSTOMER(CUSTOMERCODE), FOREIGN KEY (COUPON) REFERENCES COUPON(COUPONID), FOREIGN KEY (STOREID) REFERENCES STORE(STOREID), FOREIGN KEY (CREATEDUSERID) REFERENCES USER(USERID));
HOLDBILLDETAIL (HOLDBILLDETAILID NUMBER PRIMARY KEY, HOLDBILLNO NUMBER, PRODUCTCODE NUMBER, ORDERQTY NUMBER, SELLINGPRICE NUMBER, NETPURCHASEPRICE NUMBER, MRP NUMBER, HSNCODE NUMBER, GROSSAMOUNT NUMBER, DISCOUNT NUMBER, REDEEMAMOUNT TEXT, COUPONAMOUNT NUMBER, ALLOWFRACTION BOOLEAN, MEMBERDISCOUNT BOOLEAN, TAXDESCRIPTION TEXT, NETAMOUNT NUMBER, ISACTIVE BOOLEAN, FREECODE NUMBER, FOREIGN KEY (HOLDBILLNO) REFERENCES HOLDBILL(HOLDBILLNO), FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE), FOREIGN KEY (FREECODE) REFERENCES PRODUCT(PRODUCTCODE));
HOLDPURCHASE (HOLDGRNNO NUMBER PRIMARY KEY, HOLDGRNDATE TIMESTAMP_NTZ, INVOICENO TEXT, INVOICEDATE TIMESTAMP_NTZ, INVOICEAMOUNT NUMBER, SUPPLIERID NUMBER, STOREID NUMBER, PAYMODEID NUMBER, ISGRN BOOLEAN, CREATEDUSERID NUMBER, ISACTIVE BOOLEAN, PONO NUMBER, PARENTGRNNO TEXT, FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIER(SUPPLIERID), FOREIGN KEY (STOREID) REFERENCES STORE(STOREID), FOREIGN KEY (PAYMODEID) REFERENCES PAYMODE(PAYMODEID), FOREIGN KEY (CREATEDUSERID) REFERENCES USER(USERID), FOREIGN KEY (PONO) REFERENCES PURCHASEORDER(POID));
HOLDPURCHASEDETAIL (HOLDPURCHASEDETAILID NUMBER PRIMARY KEY, HOLDGRNNO NUMBER, PRODUCTCODE NUMBER, BATCHID NUMBER, RECEIVEDQTY NUMBER, FREEQTY NUMBER, FREEPRODUCTCODE NUMBER, BASECOST NUMBER, PURCHASEPRICEWITHTAX NUMBER, NETPURCHASEPRICE NUMBER, INCLUDEREGDIS BOOLEAN, INCLUDESPLDIS BOOLEAN, SELLINGPRICE NUMBER, WHOLESALEPRICE1 NUMBER, WHOLESALEPRICE2 NUMBER, WHOLESALEPRICE3 NUMBER, MRP NUMBER, REGDISPERCENTAGE NUMBER, REGDISAMOUNT NUMBER, SPLDISPERCENTAGE NUMBER, SPLDISAMOUNT NUMBER, HSNCODE TEXT, TAXDESCRIPTION TEXT, TAXPERCENT NUMBER, TAXAMOUNT NUMBER, SGSTAMOUNT NUMBER, CGSTAMOUNT NUMBER, CESSAMOUNT NUMBER, IGSTAMOUNT NUMBER, BASECOSTTOTAL NUMBER, NETCOST NUMBER, ISACTIVE BOOLEAN, GROCERYBRAND NUMBER, PURCHASEHOLDREASONID NUMBER, FOREIGN KEY (HOLDGRNNO) REFERENCES HOLDPURCHASE(HOLDGRNNO), FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE), FOREIGN KEY (BATCHID) REFERENCES BATCH(BATCHID), FOREIGN KEY (FREEPRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE), FOREIGN KEY (PURCHASEHOLDREASONID) REFERENCES PURCHASEHOLDREASON(PURCHASEHOLDREASONID));
HOLDTRANSFER (TRANSFEROUTHOLDNO NUMBER PRIMARY KEY, HOLDON TIMESTAMP_NTZ, TINSTOREID NUMBER, TRANSFERREQNO TEXT, GRNNO TEXT, TOTALAMOUNT NUMBER, TRANSFERTYPEID NUMBER, ISTRANSFERRED BOOLEAN, ISACTIVE BOOLEAN, CREATEDUSERID NUMBER, FOREIGN KEY (TINSTOREID) REFERENCES STORE(STOREID), FOREIGN KEY (TRANSFERTYPEID) REFERENCES TRANSFERTYPE(TRANSFERTYPEID), FOREIGN KEY (CREATEDUSERID) REFERENCES USER(USERID))
HOLDTRANSFERDETAIL (TRANSFEROUTHOLDDETAILID NUMBER PRIMARY KEY, TRANSFEROUTHOLDNO NUMBER, PRODUCTCODE NUMBER, QTY NUMBER, MRP NUMBER, BASECOST NUMBER, PURCHASEPRICEWITHTAX NUMBER, NETPURCHASEPRICE NUMBER, SELLINGPRICE NUMBER, TAXID NUMBER, TAXAMOUNT NUMBER, NETCOST NUMBER, ISACTIVE BOOLEAN, BATCHID NUMBER, FOREIGN KEY (TRANSFEROUTHOLDNO) REFERENCES HOLDTRANSFER(TRANSFEROUTHOLDNO), FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE), FOREIGN KEY (TAXID) REFERENCES TAX(TAXID), FOREIGN KEY (BATCHID) REFERENCES BATCH(BATCHID))
IBMAGENTOSTOCK (SKU TEXT PRIMARY KEY, NAME TEXT, WEIGHT NUMBER, PARENT_CODE NUMBER, PRICE NUMBER, SPECIAL_PRICE NUMBER, QTY NUMBER, FOREIGN KEY (PARENT_CODE) REFERENCES IBMAGENTOSTOCK(SKU))
IBOUTSOURCESBRAND (OUTSOURCECODE NUMBER PRIMARY KEY, BRANDCODE NUMBER, ISACTIVE BOOLEAN, FOREIGN KEY (BRANDCODE) REFERENCES BRAND(BRANDID))
IBOUTSOURCESSUPPLIERMARGINS (ID NUMBER PRIMARY KEY, SUPPLIERCODE NUMBER, PURCHASEMARGIN NUMBER, MRPMARGIN NUMBER, CREATEDDATE TIMESTAMP_NTZ, ISACTIVE BOOLEAN, FOREIGN KEY (SUPPLIERCODE) REFERENCES SUPPLIER(SUPPLIERID))
IBSHOPSTOCK (PRODUCTCODE NUMBER PRIMARY KEY, PRODUCTNAME TEXT, MRP NUMBER, SALEPRICE NUMBER, STOCK NUMBER, FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE))
IBSUBCATEGORYXMMSSUBCATEGORY (IBSUBCATEGORYXMMSSUBCATEGORYID NUMBER PRIMARY KEY, IBSUBCATEGORYID NUMBER, MMSSUBCATEGORYID NUMBER, ISACTIVE BOOLEAN, FOREIGN KEY (IBSUBCATEGORYID) REFERENCES SUBCATEGORY(SUBCATEGORYID), FOREIGN KEY (MMSSUBCATEGORYID) REFERENCES SUBCATEGORY(SUBCATEGORYID))
LOGINLOGDETAIL (LOGINID NUMBER PRIMARY KEY, DATETIME TIMESTAMP_NTZ, USERNAME NUMBER, PASSWORD TEXT, SYSTEM TEXT, LOGINSTATUS NUMBER, MODULEID TEXT, FOREIGN KEY (USERNAME) REFERENCES USER(USERID), FOREIGN KEY (MODULEID) REFERENCES MODULE(MODULEID))
MODIFICATIONLOG (UPDATEDON TIMESTAMP_NTZ, OLDVALUE TEXT, NEWVALUE TEXT, AUTOMATETASKID NUMBER, UPDATEDBY NUMBER, FOREIGN KEY (AUTOMATETASKID) REFERENCES AUTOMATETASK(AUTOMATELISTID), FOREIGN KEY (UPDATEDBY) REFERENCES USER(USERID))
MODULE (MODULEID NUMBER PRIMARY KEY, DESCRIPTIONS TEXT, ISACTIVE BOOLEAN)
MODULEVERSION (MODULEID NUMBER, MODULENAME TEXT, REQUIREDVERSION NUMBER, ISACTIVE BOOLEAN, PRIMARY KEY (MODULEID), FOREIGN KEY (MODULEID) REFERENCES MODULE(MODULEID))
MONTHLYGIFT (MONTHLYGIFTID NUMBER PRIMARY KEY, OFFERNAME TEXT, FREEPRODUCTCODE NUMBER, FROMDATE DATE, TODATE DATE, MINSALEVALUE NUMBER, MAXSALEVALUE NUMBER, ISACTIVE BOOLEAN, FOREIGN KEY (FREEPRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE))
MONTHLYGIFTDETAIL (MONTHLYGIFTDETAILID NUMBER PRIMARY KEY, MONTHLYGIFTID NUMBER, BILLNO NUMBER, REDEEMDATE TIMESTAMP_NTZ, FREEPRODUCTCODE NUMBER, QTY NUMBER, GIFTVALUE NUMBER, REDEEMAMOUNT NUMBER, FOREIGN KEY (MONTHLYGIFTID) REFERENCES MONTHLYGIFT(MONTHLYGIFTID), FOREIGN KEY (BILLNO) REFERENCES PRODUCTSALE(BILLNO), FOREIGN KEY (FREEPRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE))
NEWFORMNAME (FORMNAME TEXT PRIMARY KEY, MODULEID NUMBER, FOREIGN KEY (MODULEID) REFERENCES MODULE(MODULEID))
NONIBPRODUCT (MAGENTOCODE TEXT PRIMARY KEY, PRODUCTNAME TEXT, PARENTCODE NUMBER, WEIGHT NUMBER, ISSYNCED BOOLEAN, FOREIGN KEY (PARENTCODE) REFERENCES NONIBPRODUCT(MAGENTOCODE))
NOTIFY (NOTIFYID NUMBER PRIMARY KEY, MODULE TEXT, STOREID NUMBER, EMAILID TEXT, MOBILENO TEXT, FOREIGN KEY (STOREID) REFERENCES STORE(STOREID))
OFFERPRODUCT (OFFERPRODUCTID NUMBER PRIMARY KEY, PRODUCTCODE NUMBER, PURCHASEPRICEWITHTAX NUMBER, SALEPRICE NUMBER, MRP NUMBER, OFFERPRICE NUMBER, FROMDATE DATE, TODATE DATE, TAXID NUMBER, CREATEDUSERID NUMBER, CREATEDDATE TIMESTAMP_NTZ, ISACTIVE BOOLEAN, FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE), FOREIGN KEY (TAXID) REFERENCES TAX(TAXID), FOREIGN KEY (CREATEDUSERID) REFERENCES USER(USERID))
ONLINEORDER (ORDERID NUMBER PRIMARY KEY, STOREID NUMBER, ORDERDATE TIMESTAMP_NTZ, TOTALITEMS NUMBER, TOTALQTY NUMBER, ORDERAMOUNT NUMBER, DISCOUNTAMOUNT NUMBER, DELIVERYAMOUNT NUMBER, TOTALAMOUNT NUMBER, PAYMENTMETHOD TEXT, CUSTOMERNAME TEXT, ADDRESS TEXT, CITY TEXT, STATE TEXT, MOBILENO NUMBER, EMAIL TEXT, PINCODE NUMBER, DELIVERYSLOT TEXT, ISBILLED BOOLEAN, ISSYNCED BOOLEAN, FOREIGN KEY (STOREID) REFERENCES STORE(STOREID))
ONLINEORDERDETAIL (ORDERDETAILID NUMBER PRIMARY KEY, ORDERID NUMBER, PRODUCTCODE NUMBER, MRP NUMBER, SALEPRICE NUMBER, QTY NUMBER, ISACTIVE BOOLEAN, FOREIGN KEY (ORDERID) REFERENCES ONLINEORDER(ORDERID), FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE))
OUTSOURCEPLUSERIES (PRODUCTCODE NUMBER PRIMARY KEY, PLUNO NUMBER, FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE))
PAYMENTTYPE (PAYMENTTYPEID NUMBER PRIMARY KEY, DESCRIPTIONS TEXT, ISACTIVE BOOLEAN)
PAYMODE (PAYMODEID NUMBER PRIMARY KEY, DESCRIPTIONS TEXT, ISPURCHASE BOOLEAN, ISACTIVE BOOLEAN)
PENDINGSUPPLIERPAYMENT (PENDINGSUPPLIERPAYMENTID NUMBER PRIMARY KEY, DATE DATE, SUPPLIERID NUMBER, GRNNO NUMBER, NETAMOUNT NUMBER, FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIER(SUPPLIERID), FOREIGN KEY (GRNNO) REFERENCES PURCHASE(GRNNO))
POTYPE (POTYPEID NUMBER PRIMARY KEY, DESCRIPTIONS TEXT, ISACTIVE BOOLEAN)
PRICECHANGE (PRICECHANGEID NUMBER PRIMARY KEY, PRICECHANGEDATE TIMESTAMP_NTZ, PRODUCTCODE NUMBER, STORETYPEID NUMBER, MARGINTYPE TEXT, PURCHASEPRICE NUMBER, MRP NUMBER, SALEPRICE NUMBER, WSPRICE1 NUMBER, WSPRICE2 NUMBER, WSPRICE3 NUMBER, SALEPRICEPERCENTAGE NUMBER, WSPRICE1PERCENTAGE NUMBER, WSPRICE2PERCENTAGE NUMBER, WSPRICE3PERCENTAGE NUMBER, SALEPRICEAMOUNT NUMBER, WSPRICE1AMOUNT NUMBER, WSPRICE2AMOUNT NUMBER, WSPRICE3AMOUNT NUMBER, PRODUCTIONCOST NUMBER, PMARGINTYPE TEXT, PPURCHASEPRICE NUMBER, PMRP NUMBER, PSALEPRICE NUMBER, PWSPRICE1 NUMBER, PWSPRICE2 NUMBER, PWSPRICE3 NUMBER, PSALEPRICEPERCENTAGE NUMBER, PWSPRICE1PERCENTAGE NUMBER, PWSPRICE2PERCENTAGE NUMBER, PWSPRICE3PERCENTAGE NUMBER, PSALEPRICEAMOUNT NUMBER, PWSPRICE1AMOUNT NUMBER, PWSPRICE2AMOUNT NUMBER, PWSPRICE3AMOUNT NUMBER, PPRODUCTIONCOST NUMBER, USERID NUMBER, ISUPDATE BOOLEAN, ISACTIVE BOOLEAN, FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE),FOREIGN KEY (STORETYPEID) REFERENCES STORETYPE(STORETYPEID))
PRICETALKER (PRICETALKERNO NUMBER PRIMARY KEY, USERID NUMBER, CREATEDDATE TIMESTAMP_NTZ, ISACTIVE BOOLEAN, FOREIGN KEY (USERID) REFERENCES USER(USERID))
PRICETALKERDETAIL (PRICETALKERID NUMBER PRIMARY KEY, PRICETALKERNO NUMBER, PRODUCTCODE NUMBER, SALEPRICE NUMBER, MRP NUMBER, ISACTIVE BOOLEAN, FOREIGN KEY (PRICETALKERNO) REFERENCES PRICETALKER(PRICETALKERNO),FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE))
PRODUCT (PRODUCTCODE NUMBER PRIMARY KEY, PRODUCTNAME TEXT, PRODUCTSHORTNAME TEXT, SUPPLIERID NUMBER, SUBCATEGORYID NUMBER, BRANDID NUMBER, MANUFACTURERID NUMBER, UOMID NUMBER, CASEQTY NUMBER, BAYID TEXT, SHELFID TEXT, HSNCODE NUMBER, TAXID NUMBER, MINQTY NUMBER, MAXQTY NUMBER, ORDERQTY NUMBER, PRODUCTIONCOST NUMBER, MRP NUMBER, PURCHASEPRICE NUMBER, PURCHASEPRICEWITHTAX NUMBER, DISCOUNTPERCENTAGE NUMBER, DISCOUNTAMOUNT NUMBER, SPLDISPERCENTAGE NUMBER, SPLDISAMOUNT NUMBER, MARGINTYPE TEXT, SALEPRICE NUMBER, WHOLESALEPRICE1 NUMBER, WHOLESALEPRICE2 NUMBER, WHOLESALEPRICE3 NUMBER, SALEPRICEPERCENTAGE NUMBER, WHOLESALEPRICE1PERCENTAGE NUMBER, WHOLESALEPRICE2PERCENTAGE NUMBER, WHOLESALEPRICE3PERCENTAGE NUMBER, SALEPRICEPERAMOUNT NUMBER, WSPRICE1PERAMOUNT NUMBER, WSPRICE2PERAMOUNT NUMBER, WSPRICE3PERAMOUNT NUMBER, ISPARENT BOOLEAN, WEIGHT NUMBER, PARENTPRODUCTCODE NUMBER, ISEXPIRE BOOLEAN, EXPIRYDAYS NUMBER, ISALLOWFRACTION BOOLEAN, ISFREE BOOLEAN, ISLOYALTY BOOLEAN, ISBATCH BOOLEAN, ISMEMBERDISCOUNT BOOLEAN, ISCHECKSTOCK BOOLEAN, ISAUTOPOALLOWED BOOLEAN, ISSHOWPURCHASERETURN BOOLEAN, ISSHOWSALESRETURN BOOLEAN, ISSHOWBILLING BOOLEAN, ISSHOWGRN BOOLEAN, ISSHOWPO BOOLEAN, ISACTIVE BOOLEAN, ISTHIRDPARTYPRODUCT BOOLEAN, ISCOMBO BOOLEAN, ISHIDEONLINE BOOLEAN, CREATEDUSERID NUMBER, CREATEDDATE TEXT, MODIFIEDUSERID NUMBER, MODIFIEDDATE TEXT, STOCKDAYS NUMBER, FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIER(SUPPLIERID),FOREIGN KEY (SUBCATEGORYID) REFERENCES SUBCATEGORY(SUBCATEGORYID),FOREIGN KEY (BRANDID) REFERENCES BRAND(BRANDID),FOREIGN KEY (MANUFACTURERID) REFERENCES MANUFACTURER(MANUFACTURERID),FOREIGN KEY (TAXID) REFERENCES TAX(TAXID))
PRODUCTSALE (BILLNO NUMBER PRIMARY KEY, BILLDATE TIMESTAMP_NTZ, NETDISCOUNT NUMBER, TOTALTAXAMOUNT NUMBER, OTHERAMOUNT NUMBER, CGSTAMOUNT NUMBER, SGSTAMOUNT NUMBER, CESSAMOUNT NUMBER, ROUNDOFF NUMBER, TENDERAMOUNT NUMBER, PAYMODE1ID NUMBER, PAYMODE1AMOUNT NUMBER, PAYMODE2ID NUMBER, PAYMODE2AMOUNT NUMBER, NETAMOUNT NUMBER, RETURNBILLAMOUNT NUMBER, CUSTOMERCODE NUMBER, CUSTOMERTYPEID NUMBER, DISCOUNTPERCENTAGE NUMBER, DISCOUNTAUTHORISEDBY NUMBER, DISCOUNTUSERID NUMBER, DISCOUNTTYPEID TEXT, REDEEMVALUE NUMBER, EARNEDPOINT NUMBER, COUPONID NUMBER, COUPONAMOUNT NUMBER, GROSSAMOUNT NUMBER, SYSTEMID NUMBER, TOTALITEM NUMBER, TOTALQTY NUMBER, TOTALSAVINGAMOUNT NUMBER, CREATEDUSERID NUMBER, RETURNUSERID NUMBER, MODIFIEDDATE TIMESTAMP_NTZ, CORPORATECOUPONID NUMBER, ORDERID NUMBER, TOTALBILLTIMESEC NUMBER, ISACTIVE BOOLEAN, ISSYNCED BOOLEAN, FOREIGN KEY (PAYMODE1ID) REFERENCES PAYMODE(PAYMODEID),FOREIGN KEY (PAYMODE2ID) REFERENCES PAYMODE(PAYMODEID),FOREIGN KEY (CUSTOMERCODE) REFERENCES CUSTOMERACCOUNT(CUSTOMERCODE),FOREIGN KEY (DISCOUNTTYPEID) REFERENCES DISCOUNTTYPE(DISCOUNTTYPEID),FOREIGN KEY (ORDERID) REFERENCES ONLINEORDER(ORDERID))
PRODUCTSALEDETAIL (PRODUCTSALEDETAILID NUMBER PRIMARY KEY, BILLNO NUMBER, PRODUCTCODE NUMBER, FREECODE NUMBER, QUANTITY NUMBER, RETURNQUANTITY NUMBER, NETPURCHASEPRICE NUMBER, PURCHASEPRICEWITHTAX NUMBER, ACTUALSALEPRICE NUMBER, SALEPRICE NUMBER, MRP NUMBER, DISCOUNTAMOUNT NUMBER, COUPONAMOUNT NUMBER, REDEEMEDPOINTAMOUNT TEXT, TOTALAMOUNT NUMBER, TAXPERCENT NUMBER, BATCHID NUMBER, CURRENTSTOCK NUMBER, HSNID NUMBER, ISACTIVE BOOLEAN, ISCOMBOPRODUCT BOOLEAN, ISOFFERPRODUCT BOOLEAN, ISBILLVALUEPRODUCT BOOLEAN, FOREIGN KEY (BILLNO) REFERENCES PRODUCTSALE(BILLNO),FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE),FOREIGN KEY (BATCHID) REFERENCES BATCH(BATCHID),FOREIGN KEY (HSNID) REFERENCES TAXHSNCODE(HSNID))
PRODUCTSALETAXDETAIL (PRODUCTSALETAXDETAILID NUMBER PRIMARY KEY, BILLNO NUMBER, TAXID NUMBER, GROSSAMOUNT NUMBER, TAXAMOUNT NUMBER, CESSAMOUNT NUMBER, NETAMOUNT NUMBER, ISACTIVE BOOLEAN, FOREIGN KEY (BILLNO) REFERENCES PRODUCTSALE(BILLNO),FOREIGN KEY (TAXID) REFERENCES TAX(TAXID))
PURCHASE (GRNNO NUMBER PRIMARY KEY, GRNDATE TIMESTAMP_NTZ, INVOICENO TEXT, INVOICEDATE TIMESTAMP_NTZ, INVOICEAMOUNT NUMBER, SUPPLIERID NUMBER, STOREID NUMBER, PAYMODEID NUMBER, TOTALBASEAMOUNT NUMBER, TOTALREGDISAMT NUMBER, TOTALSPLDISAMT NUMBER, TOTALTAXAMOUNT NUMBER, TOTALCGSTAMOUNT NUMBER, TOTALSGSTAMOUNT NUMBER, TOTALCESSAMOUNT NUMBER, TOTALIGSTAMOUNT NUMBER, CASHDISCOUNTPERCENTAGE NUMBER, CASHDISCOUNTAMOUNT NUMBER, EXPENSEID NUMBER, EXPENSEAMOUNT NUMBER, ADJUSTMENTAMOUNT NUMBER, TOTALNETAMOUNT NUMBER, GRNSTATUSID NUMBER, ISIGST BOOLEAN, REMARKS TEXT, PURCHASERETURNNO TEXT, RETURNAMOUNT NUMBER, USERID NUMBER, ISOUTSOURCE BOOLEAN, ISACTIVE BOOLEAN, MODIFIEDDATE TIMESTAMP_NTZ, PONO NUMBER, PARENTGRNNO TEXT, PRINTCOUNT NUMBER, FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIER(SUPPLIERID),FOREIGN KEY (STOREID) REFERENCES STORE(STOREID),FOREIGN KEY (PAYMODEID) REFERENCES PAYMODE(PAYMODEID),FOREIGN KEY (GRNSTATUSID) REFERENCES RETURNSTATUS(RETURNSTATUSID))
PURCHASEDETAIL (PURCHASEDETAILID NUMBER PRIMARY KEY, GRNNO NUMBER, PRODUCTCODE NUMBER, BATCHID NUMBER, RECEIVEDQTY NUMBER, FREEQTY NUMBER, FREEPRODUCTCODE NUMBER, BASECOST NUMBER, PURCHASEPRICEWITHTAX NUMBER, NETPURCHASEPRICE NUMBER, SELLINGPRICE NUMBER, WHOLESALEPRICE1 NUMBER, WHOLESALEPRICE2 NUMBER, WHOLESALEPRICE3 NUMBER, MRP NUMBER, MARKUPPERCENT NUMBER, REGDISPERCENTAGE NUMBER, REGDISAMOUNT NUMBER, SPLDISPERCENTAGE NUMBER, SPLDISAMOUNT NUMBER, HSNCODE NUMBER, TAXDESCRIPTION TEXT, TAXPERCENT NUMBER, TAXAMOUNT NUMBER, SGSTAMOUNT NUMBER, CGSTAMOUNT NUMBER, CESSAMOUNT NUMBER, IGSTAMOUNT NUMBER, BASECOSTTOTAL NUMBER, NETCOST NUMBER, ISACTIVE BOOLEAN, FOREIGN KEY (GRNNO) REFERENCES PURCHASE(GRNNO),FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE),FOREIGN KEY (BATCHID) REFERENCES BATCH(BATCHID))
PURCHASEORDER (POID NUMBER PRIMARY KEY, PODATE TIMESTAMP_NTZ, TOTALITEM NUMBER, TOTALQTY NUMBER, CRITICALCOUNT TEXT, NILCOUNT NUMBER, LOWCOUNT NUMBER, CREATEDUSER NUMBER, RECEIVEDDATE TEXT)
PURCHASEORDERDETAIL (PODETAILID NUMBER PRIMARY KEY, POID NUMBER, SUPPLIERID NUMBER, PRODUCTCODE NUMBER, LASTBILLDATE TEXT, STOCKAVAILABLEDAYS TEXT, MRP TEXT, SALEQTY TEXT, STOCKQTY NUMBER, STOCKSTATUS TEXT, POQTY NUMBER, SYSTEMPO NUMBER, FOREIGN KEY (POID) REFERENCES PURCHASEORDER(POID),FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIER(SUPPLIERID),FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE))
PURCHASERETURN (PURCHASERETURNNO TEXT PRIMARY KEY, RETURNDATE TIMESTAMP_NTZ, SUPPLIERID NUMBER, STOREID NUMBER, RETURNSTATUSID NUMBER, NETAMOUNT NUMBER, REMARKS TEXT, USERID NUMBER, ISACTIVE BOOLEAN, FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIER(SUPPLIERID),FOREIGN KEY (STOREID) REFERENCES STORE(STOREID),FOREIGN KEY (RETURNSTATUSID) REFERENCES RETURNSTATUS(RETURNSTATUSID))
PURCHASERETURNACCOUNT (PURCHASERETURNACCOUNTID NUMBER PRIMARY KEY, ADJUSTMENTDATE TIMESTAMP_NTZ, PURCHASERETURNNO TEXT, GRNNO NUMBER, ADJUSTMENTAMOUNT NUMBER, USERID NUMBER, ISACTIVE BOOLEAN, FOREIGN KEY (PURCHASERETURNNO) REFERENCES PURCHASERETURN(PURCHASERETURNNO),FOREIGN KEY (GRNNO) REFERENCES PURCHASE(GRNNO))
PURCHASERETURNDETAIL (PURCHASERETURNDETAILID NUMBER PRIMARY KEY, PURCHASERETURNNO TEXT, GRNRETURNREQUESTNO TEXT, GRNRETURNREQUESTID NUMBER, PRODUCTCODE NUMBER, RETURNREASONID NUMBER, REQUESTQTY NUMBER, REPLACEMENTQTY NUMBER, RETURNQTY NUMBER, MRP NUMBER, SALEPRICE NUMBER, PURCHASEPRICE NUMBER, BASECOST NUMBER, TOTALCOST NUMBER, REGDISPERCENTAGE NUMBER, REGDISAMOUNT NUMBER, SPLDISPERCENTAGE NUMBER, SPLDISAMOUNT NUMBER, NETAMOUNT NUMBER, HSNCODE NUMBER, TAXDESCRIPTION TEXT, TAXPERCENTAGE NUMBER, TAXAMOUNT NUMBER, CGSTAMOUNT NUMBER, SGSTAMOUNT NUMBER, CESSAMOUNT NUMBER, IGSTAMOUNT NUMBER, BATCHID NUMBER, ISACTIVE BOOLEAN, FOREIGN KEY (PURCHASERETURNNO) REFERENCES PURCHASERETURN(PURCHASERETURNNO),FOREIGN KEY (GRNRETURNREQUESTID) REFERENCES PURCHASERETURNREQUEST(GRNRETURNREQUESTID),FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE),FOREIGN KEY (RETURNREASONID) REFERENCES RETURNREASON(RETURNREASONID))
PURCHASERETURNREQUEST (PURCHASERETURNREQUESTNO TEXT PRIMARY KEY, RETURNREQUESTDATE TIMESTAMP_NTZ, SUPPLIERID NUMBER, STOREID NUMBER, RETURNREQUESTSTATUSID NUMBER, REMARKS TEXT, USERID NUMBER, ISACTIVE BOOLEAN, FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIER(SUPPLIERID),FOREIGN KEY (STOREID) REFERENCES STORE(STOREID),FOREIGN KEY (RETURNREQUESTSTATUSID) REFERENCES RETURNSTATUS(RETURNREQUESTSTATUSID))
PURCHASERETURNREQUESTDETAIL (PURCHASERETURNREQUESTDETAILID NUMBER PRIMARY KEY, PURCHASERETURNREQUESTNO TEXT, PRODUCTCODE NUMBER, BATCHID NUMBER, RETURNREASONID NUMBER, QTY NUMBER, ACCEPTQTY NUMBER, BASECOST NUMBER, PURCHASEPRICEWITHTAX NUMBER, SELLINGPRICE NUMBER, MRP NUMBER, REGDISPERCENTAGE NUMBER, REGDISAMOUNT NUMBER, SPLDISPERCENTAGE NUMBER, SPLDISAMOUNT NUMBER, HSNCODE NUMBER, TAXDESCRIPTION TEXT, TAXPERCENT NUMBER, TAXAMOUNT NUMBER, SGSTAMOUNT NUMBER, CGSTAMOUNT NUMBER, CESSAMOUNT NUMBER, IGSTAMOUNT NUMBER, NETCOST NUMBER, RETURNREQUESTSTATUSID NUMBER, ISRETURNCOMPLETE BOOLEAN, ISACTIVE BOOLEAN, FOREIGN KEY (PURCHASERETURNREQUESTNO) REFERENCES PURCHASERETURNREQUEST(PURCHASERETURNREQUESTNO),FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE),FOREIGN KEY (BATCHID) REFERENCES BATCH(BATCHID),FOREIGN KEY (RETURNREASONID) REFERENCES RETURNREASON(RETURNREASONID))
PURCHASERETURNREQUESTHOLD (HOLDRETURNREQUESTNO NUMBER PRIMARY KEY, HOLDRETURNREQUESTDATE TIMESTAMP_NTZ, USERID NUMBER, ISACTIVE BOOLEAN, FOREIGN KEY (USERID) REFERENCES USER(USERID))
PURCHASERETURNREQUESTHOLDDETAIL (PURCHASERETURNREQUESTHOLDDETAILID NUMBER PRIMARY KEY, HOLDRETURNREQUESTNO NUMBER, PRODUCTCODE NUMBER, BATCHID NUMBER, SUPPLIERID NUMBER, RETURNREASONID NUMBER, QTY NUMBER, BASECOST NUMBER, PURCHASEPRICEWITHTAX NUMBER, SELLINGPRICE NUMBER, MRP NUMBER, REGDISPERCENTAGE NUMBER, REGDISAMOUNT NUMBER, SPLDISPERCENTAGE NUMBER, SPLDISAMOUNT NUMBER, HSNCODE NUMBER, TAXDESCRIPTION TEXT, TAXPERCENT NUMBER, TAXAMOUNT NUMBER, SGSTAMOUNT NUMBER, CGSTAMOUNT NUMBER, CESSAMOUNT NUMBER, IGSTAMOUNT NUMBER, NETCOST NUMBER, ISACTIVE BOOLEAN, FOREIGN KEY (HOLDRETURNREQUESTNO) REFERENCES PURCHASERETURNREQUESTHOLD(HOLDRETURNREQUESTNO),FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE),FOREIGN KEY (BATCHID) REFERENCES BATCH(BATCHID),FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIER(SUPPLIERID),FOREIGN KEY (RETURNREASONID) REFERENCES RETURNREASON(RETURNREASONID))
PURCHASEWAREHOUSE (ID NUMBER PRIMARY KEY, DATE DATE, GRNCOUNT NUMBER, GRNPRODUCTCOUNT NUMBER, PURCHASEQTY NUMBER, PURCHASEVALUE NUMBER, FREEQTY NUMBER, FREEVALUE NUMBER, REPLACEMENTPRODUCTCOUNT NUMBER, PURREPLACEQTY NUMBER, REPLACEMENTVALUE NUMBER, PURRRTCOUNT NUMBER, PURRRTPRODUCTCOUNT NUMBER, PURRRTQTY NUMBER, PURRRTVALUE NUMBER, GRNCANCELCOUNT NUMBER, CANCELPRODUCTCOUNT NUMBER, GRNCANCELQTY NUMBER, CANCELVALUE NUMBER)
RECEIPTENTRY (RECEIPTENTRYID NUMBER PRIMARY KEY, PAYMENTDATE DATE, PAYMODEID NUMBER, PAIDTO TEXT, CHEQUENO NUMBER, CHEQUEDATE DATE, BANKACCOUNTID NUMBER, PAIDAMOUNT NUMBER, ISCHEQUEPRINT BOOLEAN, CREATEDUSERID NUMBER, FOREIGN KEY (PAYMODEID) REFERENCES PAYMODE(PAYMODEID),FOREIGN KEY (BANKACCOUNTID) REFERENCES BANKACCOUNT(BANKACCOUNTID),FOREIGN KEY (CREATEDUSERID) REFERENCES USER(USERID))
RECEIPTENTRYDETAIL (RECEIPTENTRYDETAILID NUMBER PRIMARY KEY, RECEIPTENTRYID NUMBER, INVOICENO TEXT, INVOICEDATE DATE, VOUCHERPAYMENTID NUMBER, RECEIPTTYPEID NUMBER, RECEIPTHEADID NUMBER, PARTICULARS TEXT, CASHWITHOUTTAX NUMBER, TAXID NUMBER, GSTNUMBER TEXT, TAXAMOUNT NUMBER, AMOUNT NUMBER, FOREIGN KEY (RECEIPTENTRYID) REFERENCES RECEIPTENTRY(RECEIPTENTRYID),FOREIGN KEY (VOUCHERPAYMENTID) REFERENCES VOUCHERPAYMENT(VOUCHERPAYMENTID),FOREIGN KEY (RECEIPTTYPEID) REFERENCES RECEIPTTYPE(RECEIPTTYPEID),FOREIGN KEY (TAXID) REFERENCES TAX(TAXID))
RECEIPTHEAD (RECEIPTHEADID NUMBER PRIMARY KEY, DESCRIPTIONS TEXT, PAYMENTTYPEID NUMBER, ISACTIVE BOOLEAN, FOREIGN KEY (PAYMENTTYPEID) REFERENCES PAYMENTTYPE(PAYMENTTYPEID))
RECEIPTTYPE (RECEIPTTYPEID NUMBER PRIMARY KEY, DESCRIPTIONS TEXT, ISACTIVE BOOLEAN)
REDEEMDETAIL (REDEEMID NUMBER PRIMARY KEY, REDEEMDATE TIMESTAMP_NTZ, BILLNO NUMBER, CUSTOMERCODE NUMBER, REDEEMPOINT NUMBER, REDEEMVALUE NUMBER, ISACTIVE BOOLEAN, FOREIGN KEY (BILLNO) REFERENCES PRODUCTSALE(BILLNO),FOREIGN KEY (CUSTOMERCODE) REFERENCES CUSTOMER(CUSTOMERCODE))
RENT (RENTID NUMBER PRIMARY KEY, SHELFID NUMBER, SUPPLIERID NUMBER, ENTRYDATE DATE, RENTFORTHEMONTH DATE, RECEIVEDON DATE, RENTAMOUNT NUMBER, PAYMODEID NUMBER, CHEQUEDDNO TEXT, CHEQUEDATE TEXT, BANKID TEXT, PLACEID TEXT, BANKACCOUNTID TEXT, FOREIGN KEY (SHELFID) REFERENCES SHELF(SHELFID),FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIER(SUPPLIERID),FOREIGN KEY (PAYMODEID) REFERENCES PAYMODE(PAYMODEID),FOREIGN KEY (BANKACCOUNTID) REFERENCES BANKACCOUNT(BANKACCOUNTID))
RETURNREASON (RETURNREASONID NUMBER PRIMARY KEY, DESCRIPTIONS TEXT, ISREQUESTREASON BOOLEAN, ISACTIVE BOOLEAN)
ROLE (ROLEID NUMBER PRIMARY KEY, DESCRIPTIONS TEXT, ISACTIVE BOOLEAN)
ROLEXFORM (ROLEID NUMBER, FORMID NUMBER, RADD BOOLEAN, RDELETE BOOLEAN, RMODIFY BOOLEAN, RVIEW BOOLEAN, RPRINT BOOLEAN, PRIMARY KEY (ROLEID, FORMID), FOREIGN KEY (ROLEID) REFERENCES ROLE(ROLEID), FOREIGN KEY (FORMID) REFERENCES FORMS(FORMID))
SEX (SEXID NUMBER PRIMARY KEY, DESCRIPTIONS TEXT, ISACTIVE BOOLEAN)
SHELF (SHELFID NUMBER PRIMARY KEY, SHELFNAME TEXT, FLOORNUMBER NUMBER, RACKNUMBER NUMBER, DESCRIPTIONS TEXT, SIZEINSQFEET NUMBER, RENT NUMBER, ENABLE BOOLEAN)
STATE (STATEID NUMBER PRIMARY KEY, DESCRIPTIONS TEXT, ISACTIVE BOOLEAN, GSTSTATECODE NUMBER)
STATICIP (STATICIPID NUMBER PRIMARY KEY, STATICIP TEXT, STOREID NUMBER, ISACTIVE BOOLEAN, HOSTNAME TEXT, FOREIGN KEY (STOREID) REFERENCES STORE(STOREID))
STATUS (STATUSID NUMBER PRIMARY KEY, STATUSDESC TEXT, ISACTIVE BOOLEAN)
STOCKADJ (STOCKADJID NUMBER PRIMARY KEY, DATE TIMESTAMP_NTZ, TOTALVALUE NUMBER, TOTALQTY NUMBER, TOTALITEM NUMBER, CREATEDUSER NUMBER, FOREIGN KEY (CREATEDUSER) REFERENCES USER(USERID))
STOCKADJDETAIL (STOCKADJDETAILID NUMBER PRIMARY KEY, STOCKADJID NUMBER, BATCHID NUMBER, PRODUCTCODE NUMBER, PREVIOUSSTOCKQTY NUMBER, NEWSTOCKQTY NUMBER, ADJUSTSTOCKQTY NUMBER, PURCHASEPRICEWITHTAX NUMBER, MRP NUMBER, AMOUNT NUMBER, FOREIGN KEY (STOCKADJID) REFERENCES STOCKADJ(STOCKADJID),FOREIGN KEY (BATCHID) REFERENCES BATCH(BATCHID),FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE))
STOCKADJUSTWAREHOUSE (ID NUMBER PRIMARY KEY, DATE DATE, PRODUCTCOUNT NUMBER, PREVIOUSSTOCKQTY NUMBER, NEWSTOCKQTY NUMBER, ADJUSTQTY NUMBER, ADJUSTVALUE NUMBER)
STOCKCHECKBULK (ID NUMBER PRIMARY KEY, DATE TIMESTAMP_NTZ, PRODUCTCODE NUMBER, DIFFERENCE NUMBER, ISUPDATE BOOLEAN, FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE))
STOCKLOCATION (ID NUMBER PRIMARY KEY, FROMDATE DATE, TODATE DATE, LOCATION TEXT)
STOCKUPDATE (STOCKUPDATEID NUMBER PRIMARY KEY, STOCKDATE TIMESTAMP_NTZ, LOGIN TEXT, SKU NUMBER, ENCODE NUMBER, MRP NUMBER, QTY NUMBER, STOCKQTY NUMBER, LOCATIONID NUMBER, ISACTIVE BOOLEAN, STKTAKENBY TEXT, STKTAKENON TIMESTAMP_NTZ, FLOORROOMNAME TEXT, TOTALSTOCK NUMBER, FOREIGN KEY (LOCATIONID) REFERENCES STOCKLOCATION(ID))
STOCKWAREHOUSE (ID NUMBER PRIMARY KEY, DATE DATE, OPENINGSTOCK NUMBER, SALES NUMBER, SALESRETURN NUMBER, PURCHASE NUMBER, PURCHASEFREEQTY NUMBER, PURCHASEREPLACEMENT NUMBER, PURCHASERETURNREQUEST NUMBER, GRNCANCEL NUMBER, TRANSFERIN NUMBER, TRANSFEROUT NUMBER, WASTAGE NUMBER, ACTIVESTOCK NUMBER, NILSTOCK NUMBER, NEGSTOCK NUMBER, STOCKIN NUMBER, STOCKOUT NUMBER, TOTALSTOCK NUMBER, CLOSINGSTOCK NUMBER, OPENINGSTOCKVALUE NUMBER, CLOSINGSTOCKVALUE NUMBER)
STORE (STOREID NUMBER PRIMARY KEY, ONLINESTOREID NUMBER, STORETYPEID NUMBER, STORENAME TEXT, SHORTDESCRIPTION TEXT, GSTNUMBER TEXT, ADDRESS1 TEXT, AREAID NUMBER, CITYID NUMBER, STATEID NUMBER, PINCODE NUMBER, PHONENO TEXT, EMAIL TEXT, ISACTIVE BOOLEAN, ISCURRENTSTORE BOOLEAN, ISCURRENTSTOREWAREHOUSE BOOLEAN, CONTACTNO NUMBER, FOREIGN KEY (STORETYPEID) REFERENCES STORETYPE(STORETYPEID),FOREIGN KEY (AREAID) REFERENCES AREA(AREAID),FOREIGN KEY (CITYID) REFERENCES CITY(CITYID),FOREIGN KEY (STATEID) REFERENCES STATE(STATEID))
STORETYPE (STORETYPEID NUMBER PRIMARY KEY, DESCRIPTIONS TEXT, ISACTIVE BOOLEAN)
SUBCATEGORY (SUBCATEGORYID NUMBER PRIMARY KEY, CATEGORYID NUMBER, DESCRIPTIONS TEXT, ISACTIVE BOOLEAN, FOREIGN KEY (CATEGORYID) REFERENCES CATEGORY(CATEGORYID))
SUPPLIERACCOUNT (SUPPLIERACCOUNTID NUMBER PRIMARY KEY, DATE TIMESTAMP_NTZ, SUPPLIERID NUMBER, PONO NUMBER, GRNNO NUMBER, PURCHASERETURNNO TEXT, PAYMENTNO NUMBER, PARTICULAR TEXT, DEBITAMOUNT NUMBER, CREDITAMOUNT NUMBER, BALANCE NUMBER, USERID NUMBER, FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIER(SUPPLIERID),FOREIGN KEY (GRNNO) REFERENCES PURCHASE(GRNNO),FOREIGN KEY (PURCHASERETURNNO) REFERENCES PURCHASERETURN(PURCHASERETURNNO),FOREIGN KEY (PAYMENTNO) REFERENCES SUPPLIERPAYMENT(PAYMENTNO))
SUPPLIERDELIVERYSCHEDULE (ID NUMBER PRIMARY KEY, SUPPLIERID NUMBER, DELIVERYDAY NUMBER, DELIVERYSCHEDULEID NUMBER, ISACTIVE BOOLEAN, FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIER(SUPPLIERID),FOREIGN KEY (DELIVERYSCHEDULEID) REFERENCES DELIVERYSCHEDULE(DELIVERYSCHEDULEID))
SUPPLIERPAYMENT (PAYMENTNO NUMBER PRIMARY KEY, PAYMENTDATE TIMESTAMP_NTZ, SUPPLIERID NUMBER, PAYMODEID NUMBER, CHQDDNO NUMBER, CHQDDDATE TIMESTAMP_NTZ, BANKID TEXT, PLACEID TEXT, PAIDAMOUNT NUMBER, DISCOUNTAMOUNT NUMBER, RETURNNO TEXT, RETURNAMOUNT NUMBER, USERID NUMBER, ISCHEQUEPRINT BOOLEAN, BANKACCOUNTID NUMBER, ISCHEQUEISSUE BOOLEAN, ISCHEQUEPAID BOOLEAN, PRINTEDON TIMESTAMP_NTZ, ISSUEDON TIMESTAMP_NTZ, PAIDON TIMESTAMP_NTZ, PRINTCOUNT NUMBER, FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIER(SUPPLIERID),FOREIGN KEY (PAYMODEID) REFERENCES PAYMODE(PAYMODEID),FOREIGN KEY (BANKACCOUNTID) REFERENCES BANKACCOUNT(BANKACCOUNTID))
SUPPLIERPAYMENTDETAIL (SUPPLIERPAYMENTDETAILID NUMBER PRIMARY KEY, PAYMENTNO NUMBER, GRNNO TEXT, AMOUNT NUMBER, ISACTIVE BOOLEAN, PARENTGRNNO TEXT, FOREIGN KEY (PAYMENTNO) REFERENCES SUPPLIERPAYMENT(PAYMENTNO),FOREIGN KEY (GRNNO) REFERENCES PURCHASE(GRNNO))
SUPPLIERPAYMENTWAREHOUSE (SNO NUMBER PRIMARY KEY, PAYMENTDATE DATE, PAYMENTCOUNT NUMBER, TOTALPAIDAMOUNT NUMBER, CASHPAIDAMOUNT NUMBER, CHEQUEPAIDAMOUNT NUMBER, TOTALRETURNAMOUNT NUMBER, AVGPAIDAMOUNT NUMBER, AVGRETURNAMOUNT NUMBER, PAYMENTDISC NUMBER, PENDINGCOUNT FLOAT, PENDINGAMOUNT FLOAT, CONSIGNMENTCOUNT NUMBER, CONSIGNMENTPRODUCTS NUMBER, CONSIGNMENTQTY NUMBER, CONSIGNMENTAMOUNT NUMBER)
SUPPLIERPAYMENTXADVANCEBALANCE (SUPPLIERPAYMENTXADVANCEADJUSTID NUMBER PRIMARY KEY, PAYMENTNO NUMBER, ADVANCEBALANCEID NUMBER, ADJUSTEDAMOUNT NUMBER, FOREIGN KEY (PAYMENTNO) REFERENCES SUPPLIERPAYMENT(PAYMENTNO),FOREIGN KEY (ADVANCEBALANCEID) REFERENCES ADVANCEBALANCE(ADVANCEBALANCEID))
SUPPLIERTYPE (SUPPLIERTYPEID NUMBER PRIMARY KEY, DESCRIPTIONS TEXT, ISACTIVE BOOLEAN)
SUPPLIERXSTORE (SUPPLIERXSTOREID NUMBER PRIMARY KEY, SUPPLIERID NUMBER, STOREID NUMBER, ISACTIVE BOOLEAN, FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIER(SUPPLIERID),FOREIGN KEY (STOREID) REFERENCES STORE(STOREID))
SYNCTIME (SYNCTIMEID NUMBER PRIMARY KEY, MODULE TEXT, UPDATETIME TIMESTAMP_NTZ)
SYSTEM (SYSTEMID NUMBER PRIMARY KEY, SYSTEMNAME TEXT, IPADDRESS TEXT, MACADDRESS TEXT, ISACTIVE BOOLEAN)
TALKERNEW (TALKERNEWID NUMBER PRIMARY KEY, PRODUCTCODE NUMBER, SALEPRICE NUMBER, MRP NUMBER, TALKERFROM TIMESTAMP_NTZ, TALKERTO TIMESTAMP_NTZ, ISACTIVE BOOLEAN, FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE))
TAX (TAXID NUMBER PRIMARY KEY, TAXDESCRIPTION TEXT, GST NUMBER, SGST NUMBER, CGST NUMBER, CESS NUMBER, IGST NUMBER, ISACTIVE BOOLEAN, INTERLINKTAXID NUMBER)
TAXHSNCODE (HSNID NUMBER PRIMARY KEY, HSNCODE NUMBER, HSNCODECATEGORY TEXT, TAXID NUMBER, CREATEDUSERID NUMBER, CREATIONDATE TEXT, MODIFIEDUSERID NUMBER, MODIFIEDDATE TEXT, ISACTIVE BOOLEAN, FOREIGN KEY (TAXID) REFERENCES TAX(TAXID))
TEMPFILEERRORLOG (ERRORTIME TEXT PRIMARY KEY, ERRORMSG TEXT)
TILLINFORMATION (TILLINFORMATIONID NUMBER PRIMARY KEY, STARTDATE TIMESTAMP_NTZ, ENDDATE TIMESTAMP_NTZ, OPENINGBALANCE NUMBER, TILLVERIFYAMOUNT NUMBER, TOTALSALESAMOUNT NUMBER, CASHSALESAMOUNT NUMBER, CARDSALESAMOUNT NUMBER, ONLINESALESAMOUNT NUMBER, CREDITSALESAMOUNT NUMBER, COUPONSALESAMOUNT NUMBER, CHEQUESALESAMOUNT NUMBER, DDSALESAMOUNT NUMBER, TOTALDISCOUNTAMOUNT NUMBER, CREDITCOLLECTION NUMBER, RETURNSALESAMOUNT NUMBER, PREPAIDCOUPONAMOUNT NUMBER, REDEEMAMOUNT NUMBER, DIGITALPAYMENT NUMBER, MODIFIEDTOTALSALESAMOUNT NUMBER, MODIFIEDCASHSALESAMOUNT NUMBER, MODIFIEDCARDSALESAMOUNT NUMBER, MODIFIEDONLINESALESAMOUNT NUMBER, MODIFIEDCREDITSALESAMOUNT NUMBER, MODIFIEDCOUPONSALESAMOUNT NUMBER, MODIFIEDCHEQUESALESAMOUNT TEXT, MODIFIEDDDSALESAMOUNT TEXT, MODIFIEDTOTALDISCOUNTAMOUNT NUMBER, MODIFIEDCREDITCOLLECTION NUMBER, MODIFIEDRETURNSALESAMOUNT NUMBER, MODIFIEDPREPAIDCOUPONAMOUNT NUMBER, MODIFIEDREDEEMAMOUNT NUMBER, MODIFIEDDIGITALPAYMENT NUMBER, EXCEESORSHORT NUMBER, CASHDENOMINATION TEXT, SYSTEMID NUMBER, OPENEDUSERID NUMBER, CLOSEDUSERID NUMBER, REMARKS TEXT, ISACTIVE BOOLEAN, RELAXVALIDATION BOOLEAN, FOREIGN KEY (SYSTEMID) REFERENCES SYSTEM(SYSTEMID))
TRANSFER (TRANSFEROUTID TEXT PRIMARY KEY, TOSTOREID NUMBER, TINSTOREID NUMBER, TRANSFERINID TEXT, TODATE TIMESTAMP_NTZ, TINDATE TIMESTAMP_NTZ, TOUSERID NUMBER, TINUSERID NUMBER, ISRECEIVED BOOLEAN, PAYMODEID TEXT, TOTALBASEAMOUNT NUMBER, TOTALSPLAMOUNT NUMBER, TOTALTAXAMOUNT NUMBER, TOTALCGSTAMOUNT NUMBER, TOTALSGSTAMOUNT NUMBER, TOTALCESSAMOUNT NUMBER, TOTALIGSTAMOUNT NUMBER, CASHDISCOUNTPERCENTAGE TEXT, CASHDISCOUNTAMOUNT TEXT, ADDTIONALAMOUNT TEXT, COINADJAMOUNT TEXT, TOTALNETAMOUNT NUMBER, TRANSFEROUTSUCCESS BOOLEAN, ACKRECEIVED BOOLEAN, GRNSTATUSID NUMBER, ISIGST BOOLEAN, ISACTIVE BOOLEAN, TRANSFERREQUESTID TEXT, ISPAID BOOLEAN, TRANSFERTYPEID NUMBER, IRN TEXT)
TRANSFERDETAIL (TRANSFEROUTDETAILID TEXT PRIMARY KEY, TRANSFEROUTID TEXT, PRODUCTCODE NUMBER, TOBATCHID NUMBER, TINBATCHID NUMBER, SENDQTY NUMBER, RECEIVEDQTY NUMBER, FREEQTY NUMBER, FREECHILDCODE NUMBER, BASECOST NUMBER, PURCHASEPRICEWITHTAX NUMBER, NETPURCHASEPRICE NUMBER, SELLINGPRICE NUMBER, WHOLESALEPRICE NUMBER, MRP NUMBER, DISCOUNTAMOUNT NUMBER, DISCOUNTPERCENTAGE NUMBER, SPLPERCENTAGE NUMBER, SPLAMOUNT NUMBER, HSNCODE TEXT, TAXDESCRIPTION TEXT, TAXID NUMBER, TAXAMOUNT NUMBER, SGSTAMOUNT NUMBER, CGSTAMOUNT NUMBER, CESSAMOUNT NUMBER, IGSTAMOUNT NUMBER, BASECOSTTOTAL NUMBER, NETCOST NUMBER, ISACTIVE BOOLEAN, MODIFIEDDATE TIMESTAMP_NTZ, FOREIGN KEY (TRANSFEROUTID) REFERENCES TRANSFER(TRANSFEROUTID),FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE))
TRANSFERTYPE (TRANSFERTYPEID NUMBER PRIMARY KEY, DESCRIPTIONS TEXT, ISACTIVE BOOLEAN)
TRANSFERWAREHOUSE (ID NUMBER PRIMARY KEY, DATE DATE, TINCOUNT NUMBER, TINPRODUCTCOUNT NUMBER, TOTALTINQTY NUMBER, TINVALUE NUMBER, AVGTINVALUE NUMBER, TOUTCOUNT NUMBER, TOUTPRODUCTCOUNT NUMBER, TOTALTOUTQTY NUMBER, TOUTVALUE NUMBER, AVGTOUTVALUE NUMBER)
UOM (UOMID NUMBER PRIMARY KEY, DESCRIPTIONS TEXT, ISACTIVE BOOLEAN)
USER (USERID NUMBER PRIMARY KEY, USERNAME TEXT, PASSWORD TEXT, ROLEID NUMBER, ISACTIVE BOOLEAN, FOREIGN KEY (ROLEID) REFERENCES ROLE(ROLEID))
USERXFORM(USERID NUMBER, FORMID NUMBER, RADD BOOLEAN, RDELETE BOOLEAN, RMODIFY BOOLEAN, RVIEW BOOLEAN, RPRINT BOOLEAN, PRIMARY KEY (USERID, FORMID), FOREIGN KEY (USERID) REFERENCES USER(USERID), FOREIGN KEY (FORMID) REFERENCES FORMS(FORMID))
VERSION(VERSIONID NUMBER PRIMARY KEY, VERSION TEXT, RELESEDATE DATE, SWUPDATE TEXT, ISACTIVE BOOLEAN, ISALLOWOLDERVERSION BOOLEAN)
VOUCHEREXPENSEHEAD(VOUCHEREXPENSEHEADID NUMBER PRIMARY KEY, DESCRIPTIONS TEXT, ISACTIVE BOOLEAN, PAYMENTTYPEID NUMBER, FOREIGN KEY (PAYMENTTYPEID) REFERENCES PAYMENTTYPE(PAYMENTTYPEID))
VOUCHERPAYMENT(VOUCHERPAYMENTID NUMBER PRIMARY KEY, PAYMENTDATE DATE, PAYMODEID NUMBER, PAIDTO TEXT, CHEQUENO TEXT, CHEQUEDATE DATE, BANKID TEXT, AREAID TEXT, PAIDAMOUNT NUMBER, ISCHEQUEPRINT BOOLEAN, BANKACCOUNTID NUMBER, ISCHEQUEISSUE BOOLEAN, ISCHEQUEPAID BOOLEAN, PRINTEDON TIMESTAMP_NTZ, ISSUEDON TIMESTAMP_NTZ, PAIDON TIMESTAMP_NTZ, PRINTCOUNT NUMBER, FOREIGN KEY (PAYMODEID) REFERENCES PAYMODE(PAYMODEID), FOREIGN KEY (BANKACCOUNTID) REFERENCES BANKACCOUNT(BANKACCOUNTID))
VOUCHERPAYMENTDETAIL(VOUCHERPAYMENTDETAILID NUMBER PRIMARY KEY, VOUCHERPAYMENTID NUMBER, INVOICENO TEXT, INVOICEDATE DATE, VOUCHERHEADID NUMBER, PARTICULARS TEXT, AMOUNT NUMBER, RECEIPTENTRYID NUMBER, PAYMENTTYPEID NUMBER, CASHWITHOUTTAX NUMBER, TAXID NUMBER, GSTNUMBER TEXT, TAXAMOUNT NUMBER, FOREIGN KEY (VOUCHERPAYMENTID) REFERENCES VOUCHERPAYMENT(VOUCHERPAYMENTID), FOREIGN KEY (PAYMENTTYPEID) REFERENCES PAYMENTTYPE(PAYMENTTYPEID), FOREIGN KEY (TAXID) REFERENCES TAX(TAXID))
VOUCHERPAYMENTXADVANCEBALANCE(VOUCHERPAYMENTXADVANCEADJUSTID NUMBER PRIMARY KEY, PAYMENTNO NUMBER, ADVANCEBALANCEID NUMBER, ADJUSTEDAMOUNT NUMBER, FOREIGN KEY (PAYMENTNO) REFERENCES VOUCHERPAYMENT(VOUCHERPAYMENTID), FOREIGN KEY (ADVANCEBALANCEID) REFERENCES ADVANCEBALANCE(ADVANCEBALANCEID))
WASTAGE(WASTAGEID NUMBER PRIMARY KEY, DATE TIMESTAMP_NTZ, TOTALVALUE FLOAT, TOTALQTY FLOAT, TOTALITEM NUMBER, CREATEDUSER NUMBER, FOREIGN KEY (CREATEDUSER) REFERENCES USER(USERID))
WASTAGEDETAIL(WASTAGEDETAILID NUMBER PRIMARY KEY, WASTAGEID NUMBER, BATCHID NUMBER, PRODUCTCODE NUMBER, PREVIOUSSTOCKQTY FLOAT, WASTAGEQTY FLOAT, PURCHASEPRICEWITHTAX NUMBER, MRP FLOAT, AMOUNT FLOAT, REASON TEXT, FOREIGN KEY (WASTAGEID) REFERENCES WASTAGE(WASTAGEID), FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE), FOREIGN KEY (BATCHID) REFERENCES BATCH(BATCHID))
WASTAGEWAREHOUSE(ID NUMBER PRIMARY KEY, DATE DATE, PRODUCTCOUNT NUMBER, PREVIOUSSTOCKQTY FLOAT, WASTAGEQTY FLOAT, AFTERWASTAGESTOCKQTY FLOAT, PREVIOUSSTOCKQTYVALUE FLOAT, WASTAGEVALUE FLOAT)
PURCHASEHOLDREASON (PURCHASEHOLDREASONID NUMBER PRIMARY KEY, REASON TEXT, ISACTIVE BOOLEAN)
SALESWAREHOUSE (ID NUMBER PRIMARY KEY, BILLDATE DATE, CASH NUMBER, CARD NUMBER, CREDIT NUMBER, ONLINECASH NUMBER, ONLINECARD NUMBER, ONLINEPAYMENT NUMBER, PREPAID NUMBER, BILLCOUNT NUMBER, SALEVALUE NUMBER, SALEQTY NUMBER, GROCERYSALES NUMBER, AVGBILLVALUE NUMBER, RETURNBILLCOUNT NUMBER, TOTALRETURNVALUE NUMBER, RETURNQTY NUMBER, AVGRETURNVALE NUMBER, TOTALSALES NUMBER, PROFIT NUMBER)
SHELFASSIGN (SHELFASSIGNID NUMBER PRIMARY KEY, SHELFID NUMBER, FLOORNUMBER NUMBER, RACKNUMBER NUMBER, SIZEINSQFEET NUMBER, RENT NUMBER, SUPPLIERID NUMBER, FROMDATE DATE, TODATE TEXT,FOREIGN KEY (SHELFID) REFERENCES SHELF(SHELFID),FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIER(SUPPLIERID))
SUPPLIER (SUPPLIERID NUMBER(38,0),SUPPLIERNAME VARCHAR(16777216),SUPPLIERTYPE NUMBER(38,0),ADDRESS1 VARCHAR(16777216),ADDRESS2 VARCHAR(16777216),AREAID NUMBER(38,1),CITYID NUMBER(38,1),STATEID NUMBER(38,1),PINCODE NUMBER(38,1),GSTNUMBER VARCHAR(16777216),PANNUMBER VARCHAR(16777216),MOBILENO NUMBER(38,1),PHONE VARCHAR(16777216),EMAIL VARCHAR(16777216),CONTACTPERSONNAME VARCHAR(16777216),CONTACTPERSONMOBILENO NUMBER(38,1),CREATEDUSERID NUMBER(38,1),CREATEDDATE TIMESTAMP_NTZ(9),MODIFIEDUSERID NUMBER(38,1),MODIFIEDDATE TIMESTAMP_NTZ(9),ISACTIVE BOOLEAN,ISWHOLESALESUPPLIER BOOLEAN,CREDITPERIOD NUMBER(38,0),ISCONSIGNMENTPAYMENT BOOLEAN)

EXAMPLE
User: provide me the database name
AI: SELECT CURRENT_DATABASE();
User: list the tables in our database
AI: SHOW TABLES;
"""


@app.route("/start_conversation", methods=["POST"])
def start_conversation():
    try:
        with closing(sqlite3.connect("database.db")) as conn, closing(conn.cursor()) as cursor:
            cursor.execute("INSERT INTO conversations (title, timestamp) VALUES (?, ?)",
                           (request.json.get("title", "New Conversation"), datetime.now().strftime("%Y-%m-%d %H:%M:%S")))
            conversation_id = cursor.lastrowid
            conn.commit()
            return jsonify({"conversation_id": conversation_id})
    except sqlite3.Error as e:
        return jsonify({"error": str(e)}), 500

@app.route("/generate_sql", methods=["POST"])
def generate_sql():
    conversation_id = request.json.get("conversation_id")
    user_query = request.json.get("query")
    
    save_message(conversation_id, "user", user_query)
    
    try:
        response = openai.ChatCompletion.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content": SYSTEM_MESSAGE},
                {"role": "user", "content": user_query}
            ],
            temperature=0.25
        )
        sql_query = response["choices"][0]["message"]["content"].strip()
        save_message(conversation_id, "bot", sql_query)
        return jsonify({"sql": sql_query})
    except openai.error.OpenAIError as e:
        return jsonify({"error": str(e)}), 500

@app.route("/execute_query", methods=["POST"])
def execute_query():
    sql_query = request.json.get("query")
    if not sql_query.lower().startswith("select"):
        return jsonify({"error": "Only SELECT queries are allowed."}), 400
    response = execute_snowflake_query(sql_query)
    return jsonify(response)

@app.route("/conversation/<int:id>", methods=["GET"])
def get_conversation(id):
    try:
        with closing(sqlite3.connect("database.db")) as conn, closing(conn.cursor()) as cursor:
            cursor.execute("""
                SELECT id, role, content, timestamp FROM messages WHERE conversation_id = ? ORDER BY id
            """, (id,))
            messages = cursor.fetchall()
        return jsonify({"messages": messages})
    except sqlite3.Error as e:
        return jsonify({"error": str(e)}), 500

@app.route("/generate_chart", methods=["POST"])
def generate_chart():
    """ Handle chart generation request with error handling """
    try:
        # Parse JSON input safely
        data = request.get_json(force=True, silent=True)
        if not data:
            return jsonify({"error": "Invalid or missing JSON payload"}), 400

        chart_type = data.get("chart_type", "bar")
        num_rows = data.get("num_rows", "All")
        table = data.get("table", [])

        if not isinstance(table, list) or len(table) == 0:
            return jsonify({"error": "Table data is missing or not in correct format"}), 400

        print(f"Received data: {data}, num_rows type: {type(num_rows)}")

        # Convert table data to DataFrame
        df = pd.DataFrame(table)
        row_count = len(df)

        # Validate row count for certain chart types
        if isinstance(num_rows, str) and num_rows.lower() == "all":
            if row_count > 50 and chart_type in ["Histogram", "Bar Chart", "Line Chart", "Pie Chart"]:
                return jsonify({"warning": f"{chart_type} cannot display more than 50 rows. Your dataset has {row_count} rows."}), 200

        # Generate the prompt for AI-based chart generation
        ques = f"Create a {chart_type} using {'all rows' if str(num_rows).lower() == 'all' else f'the {num_rows} rows'} of the dataset, analyze the data and generate a meaningful chart."

        # AI-Based Smart DataFrame Processing
        df = SmartDataframe(df, config={"llm": llm})

        try:
            result = df.chat(ques)
        except Exception as ai_error:
            return jsonify({"error": f"AI processing failed: {str(ai_error)}"}), 500

        encoded_image = None

        if isinstance(result, str):
            print("Result is a string.")
            if os.path.isfile(result):  # Check if result is a valid file path
                with open(result, "rb") as image_file:
                    encoded_image = base64.b64encode(image_file.read()).decode("utf-8")
        elif isinstance(result, plt.Figure):
            buf = io.BytesIO()
            result.savefig(buf, format="png")
            buf.seek(0)
            encoded_image = base64.b64encode(buf.getvalue()).decode("utf-8")

        if not encoded_image:
            return jsonify({"error": "Unsupported response type."}), 500

        return jsonify({"status": "success", "image": encoded_image})

    except Exception as e:
        return jsonify({"error": f"Server error: {str(e)}"}), 500

@app.route("/clear_conversation", methods=["POST"])
def clear_conversation():
    conversation_id = request.json.get("conversation_id")
    try:
        with closing(sqlite3.connect("database.db")) as conn, closing(conn.cursor()) as cursor:
            # Enable foreign key constraints
            cursor.execute("PRAGMA foreign_keys = ON;")

            # Delete conversation (will also delete messages due to ON DELETE CASCADE)
            cursor.execute("DELETE FROM conversations WHERE id = ?", (conversation_id,))
            conn.commit()

        return jsonify({"message": "Conversation and linked messages deleted."})
    except sqlite3.Error as e:
        return jsonify({"error": str(e)}), 500

if __name__ == "__main__":
    init_db()
    app.run(debug=True, host="0.0.0.0", port=5000)
